apiVersion: v1
kind: Service
metadata:
  name: kubetest
spec:
  selector:
    app: kubetest
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetest
  template:
    metadata:
      labels:
        app: kubetest
    spec:
      containers:
        - name: kubetest
          image: ioneluoooo/kubetest:1.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
